apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: dev
    app: redis
  name: redis
spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
