apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml

replicas:
  - name: vote
    count: 5

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "support-sre@prod.com"