apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
  - deployment.yaml

images:
  - name: schoolofdevops/vote
    newTag: v2

replicas:
  - name: vote
    count: 2

namespace: instavote

commonLabels:
  project: instavote
  env: dev

commonAnnotations:
  supported-by: "support-sre@prod.com"

configMapGenerator:
  - name: vote-options
    env: options.env